"""Initial migration - create all tables

Revision ID: 7482f7bd8d43
Revises: 
Create Date: 2025-04-16 11:23:57.552378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7482f7bd8d43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departements'))
    )
    op.create_index(op.f('ix_departements_id'), 'departements', ['id'], unique=False)
    op.create_index(op.f('ix_departements_nom'), 'departements', ['nom'], unique=True)
    op.create_table('employes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], name=op.f('fk_employes_departement_id_departements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employes'))
    )
    op.create_index(op.f('ix_employes_email'), 'employes', ['email'], unique=True)
    op.create_index(op.f('ix_employes_id'), 'employes', ['id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_evaluation', sa.Date(), nullable=False),
    sa.Column('evaluateur', sa.String(length=100), nullable=True),
    sa.Column('score_global', sa.Float(), nullable=True),
    sa.Column('commentaires', sa.Text(), nullable=True),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], name=op.f('fk_evaluations_employe_id_employes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_index(op.f('ix_evaluations_date_evaluation'), 'evaluations', ['date_evaluation'], unique=False)
    op.create_index(op.f('ix_evaluations_employe_id'), 'evaluations', ['employe_id'], unique=False)
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_table('pointages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_pointage', sa.Date(), nullable=False),
    sa.Column('heure_arrivee', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heure_depart', sa.DateTime(timezone=True), nullable=True),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], name=op.f('fk_pointages_employe_id_employes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pointages'))
    )
    op.create_index(op.f('ix_pointages_date_pointage'), 'pointages', ['date_pointage'], unique=False)
    op.create_index(op.f('ix_pointages_employe_id'), 'pointages', ['employe_id'], unique=False)
    op.create_index(op.f('ix_pointages_id'), 'pointages', ['id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_simulation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('parametres_entree', sa.JSON(), nullable=True),
    sa.Column('resultats_simulation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], name=op.f('fk_simulations_employe_id_employes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulations'))
    )
    op.create_index(op.f('ix_simulations_date_simulation'), 'simulations', ['date_simulation'], unique=False)
    op.create_index(op.f('ix_simulations_employe_id'), 'simulations', ['employe_id'], unique=False)
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_employe_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_date_simulation'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_pointages_id'), table_name='pointages')
    op.drop_index(op.f('ix_pointages_employe_id'), table_name='pointages')
    op.drop_index(op.f('ix_pointages_date_pointage'), table_name='pointages')
    op.drop_table('pointages')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_employe_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_date_evaluation'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_employes_id'), table_name='employes')
    op.drop_index(op.f('ix_employes_email'), table_name='employes')
    op.drop_table('employes')
    op.drop_index(op.f('ix_departements_nom'), table_name='departements')
    op.drop_index(op.f('ix_departements_id'), table_name='departements')
    op.drop_table('departements')
    # ### end Alembic commands ###
